### ISSUE TITLE
Error in Clion: "unrecognized command line option ‘-mmcu=msp430g2553’"

### ISSUE THREAD

**Issue by mec-kon** [bevice/msp430_cmake_template#1]
Hello,
I opened the repository in Clion.
Unfortunately I immediately received the error message "unrecognized command line option '-mmcu=msp430g2553'".

do you know what the mistake might be?

**Comment by bevice** [comment]
I thing you’re using wrong compiler. Is it mps430-gcc?

**Comment by mec-kon** [comment]
Thank you for the quick answer.
I downloaded the msp430-gcc compiler from the official website and modified the PATH variable.
Do I have to set up a toolchain in CLion or change anything else in the settings?
This is my CMake output:

-- Current mspdebug driver is: rf2500
-- Current MCU is set to: msp430g2553
-- Current CMAKE_SYSTEM_INCLUDE_PATH: /home/linux/.msp-gcc/include
-- Set CMAKE_FIND_ROOT_PATH to /home/linux/.msp-gcc
-- Set CMAKE_SYSTEM_INCLUDE_PATH to /home/linux/.msp-gcc/include
-- Set CMAKE_SYSTEM_LIBRARY_PATH to /home/linux/.msp-gcc/lib
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linux/Dokumente/github/msp430_cmake/cmake-build-debug

Problems were encountered while collecting compiler information:
	cc: error: unrecognized command line option '-mmcu=msp430g2553'

**Comment by mec-kon** [comment]
I have set up a toolchain in the settings with 
msp430-path/bin/msp430-elf-gcc and msp430-path/bin/msp430-elf-g++ as C/C++ compiler.
After that I got an error message that MSP430_OBJCOPY cannot be found.
So I changed the path in lines 28-32 to msp430-path/bin/msp430-elf-gcc and so on.

**Comment by bevice** [comment]
Hello! 
You don't need change lines 28..32, it works well. You need to set  *MSP430_FIND_ROOT_PATH*
I've tested the template with debian jessie and it's ok.
What I do:
* install make and cmake,
* download _msp430-gcc-6.4.0.32_linux64.tar.bz2_ and  _msp430-gcc-support-files-1.204.zip_ from ti.com, extract in same directory (````~/toolchains/msp430-gcc```` for me)
* add ENV values to my .profile:
   ````export MSP430_FIND_ROOT_PATH=~/toolchains/msp430-gcc````
   ````export PATH="${MSP430_FIND_ROOT_PATH}/bin:${PATH}"````
* and use it ```` $ source ~/.profile````
* clone the template (````git clone git@... test_project````)
* create build directory and run cmake: 
   ````$ mkdir test_build && cd test_build && cmake ../test_project````
*  And build the project:
    ````$ make````

I cannot test CLion in Linux, but it use cmake with same way. Please check MSP430_FIND_ROOT_PATH env var. You can check what the cmake do with launch ````make VERBOSE=1````

**Comment by mec-kon** [comment]
Thanks again for the answer.
I only exported MSP430_FIND_ROOT_PATH, but forgot the line export PATH="${MSP430_FIND_ROOT_PATH}/bin:${PATH}".
Now it works perfectly.
